# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rev_1
    - rev_2
    - rev_3
    - rev_4
    - rev_5
    - rev_6
    - caster_left_1_joint
    - caster_left_2_joint
    - caster_right_1_joint
    - caster_right_2_joint
    - left_wheel_joint
    - right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rev_1
      - rev_2
      - rev_3
      - rev_4
      - rev_5
      - rev_6
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rev_1
    - rev_2
    - rev_3
    - rev_4
    - rev_5
    - rev_6
  gains:
    rev_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1