// Generated by gencpp from file mm_control_package/Navigation.msg
// DO NOT EDIT!


#ifndef MM_CONTROL_PACKAGE_MESSAGE_NAVIGATION_H
#define MM_CONTROL_PACKAGE_MESSAGE_NAVIGATION_H

#include <ros/service_traits.h>


#include <mm_control_package/NavigationRequest.h>
#include <mm_control_package/NavigationResponse.h>


namespace mm_control_package
{

struct Navigation
{

typedef NavigationRequest Request;
typedef NavigationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Navigation
} // namespace mm_control_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mm_control_package::Navigation > {
  static const char* value()
  {
    return "e8dc8bb776a8b70bff7d250ee9716417";
  }

  static const char* value(const ::mm_control_package::Navigation&) { return value(); }
};

template<>
struct DataType< ::mm_control_package::Navigation > {
  static const char* value()
  {
    return "mm_control_package/Navigation";
  }

  static const char* value(const ::mm_control_package::Navigation&) { return value(); }
};


// service_traits::MD5Sum< ::mm_control_package::NavigationRequest> should match
// service_traits::MD5Sum< ::mm_control_package::Navigation >
template<>
struct MD5Sum< ::mm_control_package::NavigationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mm_control_package::Navigation >::value();
  }
  static const char* value(const ::mm_control_package::NavigationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mm_control_package::NavigationRequest> should match
// service_traits::DataType< ::mm_control_package::Navigation >
template<>
struct DataType< ::mm_control_package::NavigationRequest>
{
  static const char* value()
  {
    return DataType< ::mm_control_package::Navigation >::value();
  }
  static const char* value(const ::mm_control_package::NavigationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mm_control_package::NavigationResponse> should match
// service_traits::MD5Sum< ::mm_control_package::Navigation >
template<>
struct MD5Sum< ::mm_control_package::NavigationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mm_control_package::Navigation >::value();
  }
  static const char* value(const ::mm_control_package::NavigationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mm_control_package::NavigationResponse> should match
// service_traits::DataType< ::mm_control_package::Navigation >
template<>
struct DataType< ::mm_control_package::NavigationResponse>
{
  static const char* value()
  {
    return DataType< ::mm_control_package::Navigation >::value();
  }
  static const char* value(const ::mm_control_package::NavigationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MM_CONTROL_PACKAGE_MESSAGE_NAVIGATION_H
