// Generated by gencpp from file mm_control_package/NavigationResponse.msg
// DO NOT EDIT!


#ifndef MM_CONTROL_PACKAGE_MESSAGE_NAVIGATIONRESPONSE_H
#define MM_CONTROL_PACKAGE_MESSAGE_NAVIGATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mm_control_package
{
template <class ContainerAllocator>
struct NavigationResponse_
{
  typedef NavigationResponse_<ContainerAllocator> Type;

  NavigationResponse_()
    : is_reached(false)  {
    }
  NavigationResponse_(const ContainerAllocator& _alloc)
    : is_reached(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_reached_type;
  _is_reached_type is_reached;





  typedef boost::shared_ptr< ::mm_control_package::NavigationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mm_control_package::NavigationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationResponse_

typedef ::mm_control_package::NavigationResponse_<std::allocator<void> > NavigationResponse;

typedef boost::shared_ptr< ::mm_control_package::NavigationResponse > NavigationResponsePtr;
typedef boost::shared_ptr< ::mm_control_package::NavigationResponse const> NavigationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mm_control_package::NavigationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mm_control_package::NavigationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mm_control_package::NavigationResponse_<ContainerAllocator1> & lhs, const ::mm_control_package::NavigationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_reached == rhs.is_reached;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mm_control_package::NavigationResponse_<ContainerAllocator1> & lhs, const ::mm_control_package::NavigationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mm_control_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mm_control_package::NavigationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mm_control_package::NavigationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mm_control_package::NavigationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92a498b18e821e639be1d4885d80f04c";
  }

  static const char* value(const ::mm_control_package::NavigationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92a498b18e821e63ULL;
  static const uint64_t static_value2 = 0x9be1d4885d80f04cULL;
};

template<class ContainerAllocator>
struct DataType< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mm_control_package/NavigationResponse";
  }

  static const char* value(const ::mm_control_package::NavigationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool is_reached\n"
;
  }

  static const char* value(const ::mm_control_package::NavigationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mm_control_package::NavigationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mm_control_package::NavigationResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MM_CONTROL_PACKAGE_MESSAGE_NAVIGATIONRESPONSE_H
