// Generated by gencpp from file mm_control_package/Camera.msg
// DO NOT EDIT!


#ifndef MM_CONTROL_PACKAGE_MESSAGE_CAMERA_H
#define MM_CONTROL_PACKAGE_MESSAGE_CAMERA_H

#include <ros/service_traits.h>


#include <mm_control_package/CameraRequest.h>
#include <mm_control_package/CameraResponse.h>


namespace mm_control_package
{

struct Camera
{

typedef CameraRequest Request;
typedef CameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Camera
} // namespace mm_control_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mm_control_package::Camera > {
  static const char* value()
  {
    return "010a2da2b14923ed7389c831d1e92e1f";
  }

  static const char* value(const ::mm_control_package::Camera&) { return value(); }
};

template<>
struct DataType< ::mm_control_package::Camera > {
  static const char* value()
  {
    return "mm_control_package/Camera";
  }

  static const char* value(const ::mm_control_package::Camera&) { return value(); }
};


// service_traits::MD5Sum< ::mm_control_package::CameraRequest> should match
// service_traits::MD5Sum< ::mm_control_package::Camera >
template<>
struct MD5Sum< ::mm_control_package::CameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mm_control_package::Camera >::value();
  }
  static const char* value(const ::mm_control_package::CameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mm_control_package::CameraRequest> should match
// service_traits::DataType< ::mm_control_package::Camera >
template<>
struct DataType< ::mm_control_package::CameraRequest>
{
  static const char* value()
  {
    return DataType< ::mm_control_package::Camera >::value();
  }
  static const char* value(const ::mm_control_package::CameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mm_control_package::CameraResponse> should match
// service_traits::MD5Sum< ::mm_control_package::Camera >
template<>
struct MD5Sum< ::mm_control_package::CameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mm_control_package::Camera >::value();
  }
  static const char* value(const ::mm_control_package::CameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mm_control_package::CameraResponse> should match
// service_traits::DataType< ::mm_control_package::Camera >
template<>
struct DataType< ::mm_control_package::CameraResponse>
{
  static const char* value()
  {
    return DataType< ::mm_control_package::Camera >::value();
  }
  static const char* value(const ::mm_control_package::CameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MM_CONTROL_PACKAGE_MESSAGE_CAMERA_H
