// Generated by gencpp from file mm_control_package/CameraRequest.msg
// DO NOT EDIT!


#ifndef MM_CONTROL_PACKAGE_MESSAGE_CAMERAREQUEST_H
#define MM_CONTROL_PACKAGE_MESSAGE_CAMERAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mm_control_package
{
template <class ContainerAllocator>
struct CameraRequest_
{
  typedef CameraRequest_<ContainerAllocator> Type;

  CameraRequest_()
    : camera_info()  {
    }
  CameraRequest_(const ContainerAllocator& _alloc)
    : camera_info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _camera_info_type;
  _camera_info_type camera_info;





  typedef boost::shared_ptr< ::mm_control_package::CameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mm_control_package::CameraRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraRequest_

typedef ::mm_control_package::CameraRequest_<std::allocator<void> > CameraRequest;

typedef boost::shared_ptr< ::mm_control_package::CameraRequest > CameraRequestPtr;
typedef boost::shared_ptr< ::mm_control_package::CameraRequest const> CameraRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mm_control_package::CameraRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mm_control_package::CameraRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mm_control_package::CameraRequest_<ContainerAllocator1> & lhs, const ::mm_control_package::CameraRequest_<ContainerAllocator2> & rhs)
{
  return lhs.camera_info == rhs.camera_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mm_control_package::CameraRequest_<ContainerAllocator1> & lhs, const ::mm_control_package::CameraRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mm_control_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mm_control_package::CameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mm_control_package::CameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mm_control_package::CameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mm_control_package::CameraRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mm_control_package::CameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mm_control_package::CameraRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mm_control_package::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3d1d45cc9c0eb0e6e9ef36bbe24bcd4";
  }

  static const char* value(const ::mm_control_package::CameraRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3d1d45cc9c0eb0eULL;
  static const uint64_t static_value2 = 0x6e9ef36bbe24bcd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mm_control_package::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mm_control_package/CameraRequest";
  }

  static const char* value(const ::mm_control_package::CameraRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mm_control_package::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string camera_info\n"
"\n"
;
  }

  static const char* value(const ::mm_control_package::CameraRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mm_control_package::CameraRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mm_control_package::CameraRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mm_control_package::CameraRequest_<ContainerAllocator>& v)
  {
    s << indent << "camera_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.camera_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MM_CONTROL_PACKAGE_MESSAGE_CAMERAREQUEST_H
