// Generated by gencpp from file mm_control_package/Go.msg
// DO NOT EDIT!


#ifndef MM_CONTROL_PACKAGE_MESSAGE_GO_H
#define MM_CONTROL_PACKAGE_MESSAGE_GO_H

#include <ros/service_traits.h>


#include <mm_control_package/GoRequest.h>
#include <mm_control_package/GoResponse.h>


namespace mm_control_package
{

struct Go
{

typedef GoRequest Request;
typedef GoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Go
} // namespace mm_control_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mm_control_package::Go > {
  static const char* value()
  {
    return "7da200ae649da6f1d67321388542aa84";
  }

  static const char* value(const ::mm_control_package::Go&) { return value(); }
};

template<>
struct DataType< ::mm_control_package::Go > {
  static const char* value()
  {
    return "mm_control_package/Go";
  }

  static const char* value(const ::mm_control_package::Go&) { return value(); }
};


// service_traits::MD5Sum< ::mm_control_package::GoRequest> should match
// service_traits::MD5Sum< ::mm_control_package::Go >
template<>
struct MD5Sum< ::mm_control_package::GoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mm_control_package::Go >::value();
  }
  static const char* value(const ::mm_control_package::GoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mm_control_package::GoRequest> should match
// service_traits::DataType< ::mm_control_package::Go >
template<>
struct DataType< ::mm_control_package::GoRequest>
{
  static const char* value()
  {
    return DataType< ::mm_control_package::Go >::value();
  }
  static const char* value(const ::mm_control_package::GoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mm_control_package::GoResponse> should match
// service_traits::MD5Sum< ::mm_control_package::Go >
template<>
struct MD5Sum< ::mm_control_package::GoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mm_control_package::Go >::value();
  }
  static const char* value(const ::mm_control_package::GoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mm_control_package::GoResponse> should match
// service_traits::DataType< ::mm_control_package::Go >
template<>
struct DataType< ::mm_control_package::GoResponse>
{
  static const char* value()
  {
    return DataType< ::mm_control_package::Go >::value();
  }
  static const char* value(const ::mm_control_package::GoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MM_CONTROL_PACKAGE_MESSAGE_GO_H
